pub mod acse;
pub mod activity_calendar;
pub mod association_ln;
pub mod axdr;
pub mod client;
pub mod clock;
pub mod cosem;
pub mod cosem_object;
pub mod data;
pub mod demand_register;
pub mod disconnect_control;
pub mod error;
pub mod extended_register;
pub mod hdlc;
pub mod hdlc_transport;
pub mod profile_generic;
pub mod register;
pub mod sap_assignment;
pub mod security;
pub mod security_setup;
pub mod server;
pub mod transport;
pub mod types;
pub mod wrapper_transport;
pub mod xdlms;

pub const MAX_PDU_SIZE: usize = 2048;
